### ISSUE TITLE
Duplicate structure placement

### ISSUE THREAD

**Issue by dragunoff** [AMHOL/openra-ruby#4]
I've been parsing some release-20180923 replays and noticed that sometimes two nearly identical building placements happen in the span of a few seconds. For example:
```json
        {
          "structure": "proc",
          "game_time": {
            "formatted": "00:03:30",
            "msec": 210000
          },
          "placement": {
            "x": 66,
            "y": 66
          }
        },
        {
          "structure": "proc",
          "game_time": {
            "formatted": "00:03:32",
            "msec": 212400
          },
          "placement": {
            "x": 65,
            "y": 66
          }
        },
```
Here's a replay where that occurs twice (with PROC and WEAP): http://openra.mine.nu/mIRROR/ora_replays/RAGL_Season_Six/R02/Master/RAGL-S06-MASTER-R02-NNG-ZXG-G1.orarep

**Comment by AMHOL** [comment]
Can't currently see anything in the order data that I could use to indicate whether the `PlaceBuilding` command failed or succeeded, will have to consult IRC / @pchote on this.

**Comment by AMHOL** [comment]
@dragunoff I think this was down to timing calculations being incorrect, I got help from an openra dev on Discord and they should be working as expected after https://github.com/AMHOL/openra-ruby/pull/10 (2.2.0)
